#!/bin/bash

# wrapper script for Go FIPS support

set -eu -o pipefail
shopt -qs failglob

# prefer GO_VERSION over GO_MAJOR if present, to preserve original behavior
if [ -n "${GO_VERSION:-}" ] ; then
  GO_MAJOR="${GO_VERSION%.*}"
fi

# prefer the musl flavor if GOLIBC indicates that we should
if [ "${GOLIBC:-}" = "musl" ] ; then
  GO_MAJOR+="-musl"
fi

export GOEXPERIMENT=boringcrypto
exec /usr/libexec/go-"${GO_MAJOR}"/bin/go "${@}"
