#!/usr/bin/env bash

# wrapper script to run the correct version of gofmt

set -eu -o pipefail
shopt -qs failglob

# prefer GO_VERSION over GO_MAJOR if present, to preserve original behavior
if [ -n "${GO_VERSION:-}" ] ; then
  GO_MAJOR="${GO_VERSION%.*}"
fi

# prefer the musl flavor if GOLIBC indicates that we should
if [ "${GOLIBC:-}" = "musl" ] ; then
  GO_MAJOR+="-musl"
fi

exec /usr/libexec/go-"${GO_MAJOR}"/bin/gofmt "${@}"
