[licenses]

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

allow = [
    "Apache-2.0",
    "BSL-1.0",
    "MIT",
    "Unlicense",
    "Zlib",
]

exceptions = [
    { name = "unicode-ident", allow = ["MIT", "Apache-2.0", "Unicode-3.0"] },
]

[bans]
# Deny multiple versions or wildcard dependencies.
multiple-versions = "deny"
wildcards = "deny"

skip-tree = [
    # structopt is using an older syn
    { name = "structopt", version = "0.3.26" },
]

[sources]
# Deny crates from unknown registries or git repositories.
unknown-registry = "deny"
unknown-git = "deny"
